from org.pengfei.atlas_client.client import Atlas
from org.pengfei.minio.MinioAtlasHook import MinioAtlasHook
from org.pengfei.minio.MinioClient import MinioClient
from org.pengfei.minio.S3PathClass import S3PathClass


class MinioScanner:
    def __init__(self, minio_client: MinioClient, atlas_client: Atlas, owner="unknown") -> None:
        self.minio_client = minio_client
        self.fs = minio_client.get_fs()
        self.default_owner = owner
        self.minio_atlas_hook = MinioAtlasHook(minio_client, atlas_client)

    def scan_path(self, path: str, description: str = "generated by minio atlas hook") -> None:
        sub_path_list = self.fs.ls(path)
        for sub_path in sub_path_list:
            path_class = self.minio_client.get_class_from_path(sub_path)
            current_path_meta = self.minio_client.get_path_meta_data(sub_path)
            if path_class == S3PathClass.BUCKET:
                self.minio_atlas_hook.create_atlas_bucket(current_path_meta, description)
                # call dir scanner recursively
                self.scan_path(sub_path)
            elif path_class == S3PathClass.DIR:
                self.minio_atlas_hook.create_atlas_ps_dir(current_path_meta, description)
                self.scan_path(sub_path)
            elif path_class == S3PathClass.OBJECT:
                # avoid loading .keep file
                if sub_path.split("/")[-1] == ".keep":
                    pass
                else:
                    self.minio_atlas_hook.create_atlas_object(current_path_meta, self.default_owner, description)
            else:
                raise ValueError
